# Generated by Django 5.2.8 on 2025-11-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_mission_bonus_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
