# Generated by Django 5.2.8 on 2025-11-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userprofile_last_mission_bonus_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdailymission',
            name='mission_type',
            field=models.CharField(choices=[('ichiba', '楽天市場'), ('hotel', '楽天トラベル'), ('games', '楽天ゲームズ')], max_length=20),
        ),
    ]
